[2024-06-09T04:36:46.768+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T04:36:46.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T04:36:43.984991+00:00 [queued]>
[2024-06-09T04:36:46.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T04:36:43.984991+00:00 [queued]>
[2024-06-09T04:36:46.783+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T04:36:46.789+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_upload_data> on 2024-06-09 04:36:43.984991+00:00
[2024-06-09T04:36:46.794+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1784) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T04:36:46.799+0000] {standard_task_runner.py:63} INFO - Started process 1794 to run task
[2024-06-09T04:36:46.799+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'download_upload_data', 'manual__2024-06-09T04:36:43.984991+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmp5san31wh']
[2024-06-09T04:36:46.808+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask download_upload_data
[2024-06-09T04:36:46.839+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.download_upload_data manual__2024-06-09T04:36:43.984991+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T04:36:46.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group 2' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='download_upload_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T04:36:43.984991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T04:36:43.984991+00:00'
[2024-06-09T04:36:46.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T04:36:46.888+0000] {finsight_pipeline_functions.py:21} INFO - Downloading data for NFLX from 2002-01-01 to 2022-12-31.
[2024-06-09T04:36:47.416+0000] {logging_mixin.py:188} WARNING - [*********************100%%**********************]  1 of 1 completed
[2024-06-09T04:36:47.467+0000] {finsight_pipeline_functions.py:32} ERROR - Failed to download or upload data: name 'my_dataframe' is not defined
[2024-06-09T04:36:47.468+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T04:36:47.468+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 26, in download_and_uploadToDVCBucket
    print(list(my_dataframe.columns.values))
               ^^^^^^^^^^^^
NameError: name 'my_dataframe' is not defined
[2024-06-09T04:36:47.480+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=download_upload_data, run_id=manual__2024-06-09T04:36:43.984991+00:00, execution_date=20240609T043643, start_date=20240609T043646, end_date=20240609T043647
[2024-06-09T04:36:47.488+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task download_upload_data (name 'my_dataframe' is not defined; 1794)
[2024-06-09T04:36:47.499+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T04:36:47.515+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T04:36:47.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
